CREATE PLUGGABLE DATABASE mo_pdb_26233
ADMIN USER Monrobue_plsqlauca_26233 IDENTIFIED BY simplepass
FILE_NAME_CONVERT = 
('C:\APP\ELOSPACE\PRODUCT\21C\ORADATA\XE\PDBSEED\', 'C:\APP\ELOSPACE\PRODUCT\21C\ORADATA\XE\MO_PDB_26233\');

ALTER PLUGGABLE DATABASE mo_pdb_26233 OPEN;
SELECT name, open_mode FROM v$pdbs WHERE name='MO_PDB_26233';
ALTER SESSION SET CONTAINER = mo_pdb_26233;
GRANT CONNECT, RESOURCE TO Monrobue_plsqlauca_26233;
SELECT username FROM dba_users WHERE username='MONROBUE_PLSQLAUCA_26233';

SELECT name, open_mode 
FROM v$pdbs;

