CREATE PLUGGABLE DATABASE mo_to_delete_pdb_26233
ADMIN USER Monrobue_temp_admin_26233 IDENTIFIED BY temp123
FILE_NAME_CONVERT = 
('C:\APP\ELOSPACE\PRODUCT\21C\ORADATA\XE\PDBSEED\', 'C:\APP\ELOSPACE\PRODUCT\21C\ORADATA\XE\MO_TO_DELETE_PDB_26233\');

SELECT name, open_mode 
FROM v$pdbs 
WHERE name='MO_TO_DELETE_PDB_26233';


ALTER PLUGGABLE DATABASE mo_to_delete_pdb_26233 CLOSE IMMEDIATE;


DROP PLUGGABLE DATABASE mo_to_delete_pdb_26233 INCLUDING DATAFILES;


SELECT name 
FROM v$pdbs 
WHERE name='MO_TO_DELETE_PDB_26233';
